export const LOOPS_CONFIG = [
  {
    id: "8",
    src: "loops/loop2.svg",
    width: "380vmin",
    zIndex: 20,
    duration: 55,
    direction: -1,
  },
  {
    id: "7",
    src: "loops/loop1.svg",
    width: "276vmin",
    zIndex: 30,
    duration: 50,
    direction: 1,
  },
  {
    id: "6",
    src: "loops/loop3.svg",
    width: "208vmin",
    zIndex: 10,
    duration: 45,
    direction: -1,
  },
  {
    id: "5",
    src: "loops/loop2.svg",
    width: "166vmin",
    zIndex: 20,
    duration: 40,
    direction: 1,
  },
  {
    id: "4",
    src: "loops/loop1.svg",
    width: "124vmin",
    zIndex: 30,
    duration: 35,
    direction: -1,
  },
  {
    id: "3",
    src: "loops/loop3.svg",
    width: "94vmin",
    zIndex: 10,
    duration: 30,
    direction: 1,
  },
  {
    id: "2",
    src: "loops/loop2.svg",
    width: "74vmin",
    zIndex: 20,
    duration: 25,
    direction: -1,
  },
  {
    id: "1",
    src: "loops/loop1.svg",
    width: "54vmin",
    zIndex: 30,
    duration: 20,
    direction: 1,
  },
];
