services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ragam26-main-website
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      HOSTNAME: 0.0.0.0
